OnlineShop_Project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from product.views import IndexCategories
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexCategories.as_view(), name='index'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls'))
    path('accounts/', include(('user.urls', 'user'), namespace='account')),
    path('products/', include(('product.urls', 'product'), namespace='product')),
    path('orders/', include(('order.urls', 'order'), namespace='order')),
    path('api-auth/', include('rest_framework.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path, include

from user.views import AddressCreateView
from .views import *

urlpatterns = [
    path('api/v1/', include(('order.api.v1.urls', 'api'), namespace='api')),
    path('cart/add/<str:product_name>/', ItemAddView.as_view(), name='item_add'),
    path('cartdetail/', CartView.as_view(), name='cart_detail'),
    path('cart/remove/<str:product_name>/', ItemRemoveView.as_view(), name='item_remove'),
    path('cart/create/', UserCartCreateView.as_view(), name='usercart_create'),
    path('cart/adddetail/', AddCartDetailView.as_view(), name='cartdetail_create'),
    path('usercart/', UserCartListView.as_view(), name='usercart_list'),
    path('addqty/<str:product>/', AddItemQtyView.as_view(), name='add_qty'),
    path('minusqty/<str:product>/', MinusItemQtyView.as_view(), name='minus_qty'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('add_address/<str:slug>/', AddressCreateView.as_view(template_name='order/add_address.html'), name='add_checkout_address'),

]

product/urls.py
from django.urls import path, re_path
from .views import Products, ShopCategories, ProductDetail

urlpatterns = [
    # path('', AdminIndex.as_view(), name='admin_index'),
    path('', Products.as_view(), name='all'),
    path('shop/', ShopCategories.as_view(), name='shop'),
    path('shop/<pk>', ProductDetail.as_view(), name='detail'),
    re_path(r'^(?P<slug>.*)/$', ShopCategories.as_view(), name='category'),
    # path('^shop/(?P<category>[a-zA-Z]+)/$', ShopCategories.as_view(), name='category'),
    # path('shop/chair/', ShopCategories.as_view(), name='category'),
    # path('login/', LoginPage.as_view(), name='login'),
    # path('logout/', LogoutPage.as_view(), name='logout'),

]

user/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path
from .views import *


urlpatterns = [
    # path('', AdminIndex.as_view(), name='admin_index'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('verify/', UserVerify.as_view(), name='verify'),
    path('reset/', UserPasswordReset.as_view(), name='reset_password'),
    path('reset-done/', UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('confirm-complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('profile/<str:slug>/', UserDetailView.as_view(), name='user_profile'),
    path('editprofile/<str:slug>/', UserEditView.as_view(), name='user_edit'),
    path('changepass/<str:slug>/', UserPasswordChangeView.as_view(template_name='account/change_password.html'), name='change_password'),
    path('set_default_address/<int:new_ad>/', SetDefaultAddress.as_view(), name='set_default_address'),
    path('add_address/<str:slug>/', AddressCreateView.as_view(), name='add_address'),
]

product/models.py
from datetime import date
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.text import slugify
from django.utils.translation import gettext_lazy as _
from django.utils.safestring import mark_safe
from user.models import expiry_date_validate, User


# VALIDATORS
def digit_validate(digit):
    '''
    check digit positive or not
    :param digit: entered number
    :return: None or
    :raise: ValidationError if digit is negative
    '''
    if digit <= 0:
        raise ValidationError(
            _('must be positive')
        )


# MODELS
class Category(models.Model):
    """
    define Category model for products

    ...

    Attributes
    ----------
    parent_cat : Category object
        self relation - each category can have one parent category or not ( main categories )
    name : str
        category's name
    Methods
    -------
    save:
        save the object in database
    str:
        string representation of Category object.
    """
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True)
    name = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='img/category', default='img/category/product5')

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def children(self):
        children = Category.objects.filter(parent=self.id)
        return children

    def count_children(self):
        count_child = self.children().count()
        return count_child

    def products(self):
        child = self.children()
        products = Product.objects.filter(category_id__in=[c.id for c in child] + [self.id])
        return products

    def count_products(self):
        count_products = self.products().count()
        if count_products:
            return count_products
        else:
            return '--- No Product ---'


class Product(models.Model):
    """
    define Product model

    ...

    Attributes
    ----------
    name : str
        name of the product
    category_id : int
        foreign key to Category model instance ( define product category )
    brand : str
        product brand name
    info : str
        product details & info
    proce : float
        product price
    qty : int
        product stock
    image : str
        path to the product image in project media

    Methods
    -------
    save:
        save the object in database
    str:
        string representation of Product object.
    """
    name = models.CharField(max_length=100, unique=True, primary_key=True)
    category_id = models.ForeignKey(Category, on_delete=models.DO_NOTHING)
    brand = models.CharField(max_length=50)
    info = models.TextField(max_length=300)
    price = models.FloatField(validators=[digit_validate])
    qty = models.IntegerField(validators=[digit_validate])
    image = models.ImageField(upload_to='img/product')
    slug = models.SlugField(blank=True)

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        """
        adding a slug (-) in each of the string where there is a space in name
        & put it in slug field
        & then save the object in database
        :param force_insert, force_update, using, update_fields: django default params
        :return:None
        """
        self.slug = slugify(self.name)
        super().save()

    def __str__(self):
        return f'{self.name} : {self.qty}'

    def promo(self):
        """
        this function checks that our product has promotion or not
        :return: inprocess-promo object
        :return: false if no promo
        """
        try:
            promo_obj = InProcessPromo.objects.get(product_id=self)
            if promo_obj.in_process:
                return promo_obj.promotion_id

        except:
            return False

    def price_discount(self):
        """
        this func calcs product final price with promotion value
        :return: final price of the product with or without promo
        """
        try:
            if self.promo:
                """
                if product has a promo it will be calced base on promo type 
                """
                promo = self.promo()
                if promo.type_id.name == 'cash':
                    if self.price > int(promo.hint):
                        """
                        checks minimum value to perform promo
                        """
                        return self.price - float(promo.value)
                elif promo.type_id.name == 'percentage':
                    """
                    checks maximum value of offer before perform promo
                    """
                    discount = self.price * float(promo.value)
                    if discount < int(promo.hint):
                        return self.price - discount
            else:
                return False

        except (AttributeError, ValueError):
            return False

    def final_price(self):
        if self.price_discount():
            return self.price_discount()
        return self.price


class PromotionType(models.Model):
    """
    define Promotion types for the website

    ...

    Attributes
    ----------
    name : str
        name of the promotion type

    Methods
    -------
    save:
        save the object in database
    str:
        string representation of PromotionType object.
    """
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name


class Promotion(models.Model):
    """
    define Promotion model

    ...

    Attributes
    ----------
    name : str
        name of the promotion
    type_id : int
        foreign key to PromotionType model instance ( define promotion type )
    value : float
        promotion value( in % or $ )
    hint : str
        in percentage -> maximum promotion & in cash -> minimum & in cart promo -> Discount phrase
    start_date : date
        start date of promotion
    end_date : date
        end date of promotion

    Methods
    -------
    save:
        save the object in database
    str:
        string representation of Promotion object.
    """
    name = models.CharField(max_length=50, unique=True)
    type_id = models.ForeignKey(PromotionType, on_delete=models.DO_NOTHING)
    value = models.FloatField()
    hint = models.CharField(max_length=50)
    start_date = models.DateField(default=date.today)
    end_date = models.DateField(null=False, validators=[expiry_date_validate])

    def __str__(self):
        return f'{self.name} : {self.value}'


class InProcessPromo(models.Model):
    """
    model for inprocess promotions

    ...

    Attributes
    ----------
    product_id : int
        foreign key to Product model instance
    promotion_id : int
        foreign key to Promotion model instance
    in_process : bool
        True if promotion is in-process, otherwise False

    Methods
    -------
    save:
        save the object in database
    str:
        string representation of InProcessPromo object.
    """
    product = models.ForeignKey(Product, on_delete=models.DO_NOTHING)
    promotion_id = models.ForeignKey(Promotion, on_delete=models.CASCADE)
    in_process = models.BooleanField(default=True)

    def __str__(self):
        return f'{self.promotion_id} - {self.product_id}'

    def save(
            self, force_insert=False, force_update=False, using=None, update_fields=None
    ):
        promo_end = self.promotion_id.end_date
        if expiry_date_validate(promo_end):
            if not InProcessPromo.objects.filter(product=self.product, in_process=True).exists():
                super().save()
            else:
                raise ValidationError(
                    _('This Product already has offer')
                )
        else:
            raise ValidationError(
                _('This promo is expired')
            )


class Review(models.Model):
    """
    model for Review of products

    ...

    Attributes
    ----------
    user_id : user object
        foreign key to user model ( to define review owner )
    product_id : int
        foreign key to Product model instance ( define related product )
    rating : str
        number from 1-5 to define rating stars of product
    comment : str
        user comment is stored in this field

    Methods
    -------
    save:
        save the object in database
    str:
        string representation of Review object.
    """
    RATING = [
        ('1', '1'),
        ('2', '2'),
        ('3', '3'),
        ('4', '4'),
        ('5', '5'),
    ]
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    product_id = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.CharField(max_length=1, choices=RATING)
    comment = models.TextField(max_length=600)

    def __str__(self):
        return f'* {self.rating} * : {self.comment}'

product/views.py
from django.utils.decorators import method_decorator
from django.views.generic import ListView, DetailView
from user.decorators import admin_user
from product.models import Product, Category


@method_decorator(admin_user, name='get')
class IndexCategories(ListView):
    """
    this view shows landing page of website
    all categories with image are presenting here
    """
    model = Category
    template_name = 'product/index.html'


@method_decorator(admin_user, name='get')
class ShopCategories(ListView):
    """
    this view shows shop page of website
    all products with image are presenting here
    if a category is choosen , products of that category are showing
    """
    model = Category
    template_name = 'product/shop.html'
    context_object_name = 'category_list'
    paginate_by = 6

    def get_context_data(self, **kwargs):
        """
        here we check url, if it has slug , witch is category name
        it filters products to show that category products
        :param kwargs: request data
        :return: all products if slug=none,
        :else: category and subcategories (if existed) products
        """
        context = super().get_context_data(**kwargs)

        if 'slug' in self.kwargs:
            category = Category.objects.get(name=self.kwargs['slug'])
            context['products'] = category.products()
        else:
            context['products'] = Product.objects.all()

        return context


@method_decorator(admin_user, name='get')
class ProductDetail(DetailView):
    """
    this view shows product detail
    and order link
    """
    model = Product

templates/product/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 4 meta tags *must* come first in the head; any other head content must come *after* these tags -->

    <!-- Title  -->
    <title>Amado - Furniture Ecommerce Template | Home</title>
    {% load static %}
    <!-- Favicon  -->
    <link rel="icon" href="/static/img/core-img/favicon.ico">

    <!-- Core Style CSS -->
    <link rel="stylesheet" href="/static/css/core-style.css">
    <link rel="stylesheet" href="/static/css/style.css">

</head>

<body>
    <!-- Search Wrapper Area Start -->
    <div class="search-wrapper section-padding-100">
        <div class="search-close">
            <i class="fa fa-close" aria-hidden="true"></i>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="search-content">
                        <form action="#" method="get">
                            <input type="search" name="search" id="search" placeholder="Type your keyword...">
                            <button type="submit"><img src="/static/img/core-img/search.png" alt=""></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Search Wrapper Area End -->

    <!-- ##### Main Content Wrapper Start ##### -->
    <div class="main-content-wrapper d-flex clearfix">

        <!-- Mobile Nav (max width 767px)-->
        <div class="mobile-nav">
            <!-- Navbar Brand -->
            <div class="amado-navbar-brand">
                <a href="index.html"><img src="/static/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Navbar Toggler -->
            <div class="amado-navbar-toggler">
                <span></span><span></span><span></span>
            </div>
        </div>

        <!-- Header Area Start -->
        <header class="header-area clearfix">
            <!-- Close Icon -->
            <div class="nav-close">
                <i class="fa fa-close" aria-hidden="true"></i>
            </div>
            <!-- Logo -->
            <div class="logo">
                <a href="index.html"><img src="/static/img/core-img/logo.png" alt=""></a>
            </div>
            <!-- Amado Nav -->
            <p style="color: #c7952f">Welcome {{ request.user.username }}</p>
            <nav class="amado-nav">

                <ul>
{#                    <li style="color: #c7952f">Welcome {{ request.user.username }}</li>#}

                    <li class="active"><a href="{% url 'index' %}">Home</a></li>
                    <li><a href="{% url 'product:shop' %}">Shop</a></li>
                    {% if user.is_authenticated %}
                        <li><a href="{% url 'order:usercart_list' %}">Cart</a></li>
{#                        <li><a href="checkout.html">Checkout</a></li>#}
                        <li><a href="{% url 'account:user_profile' request.user.slug %}">Profile</a></li>
                        <li><a href="{% url 'account:logout' %}">LogOut</a></li>
                    {% else %}
                        <li><a href="{% url 'account:login' %}">LogIn</a></li>
                        <li><a href="{% url 'account:register' %}">SignUp</a></li>
                    {% endif %}
                </ul>
            </nav>
            <!-- Button Group -->
            <div class="amado-btn-group mt-30 mb-100">
                <a href="#" class="btn amado-btn mb-15">%Discount%</a>
                <a href="#" class="btn amado-btn active">New this week</a>
            </div>
            <!-- Cart Menu -->
            <div class="cart-fav-search mb-100">
                <a href="{% url 'order:cart_detail' %}" class="cart-nav"><img src="/static/img/core-img/cart.png" alt=""> Cart <span>{{ cart|length }}</span></a>
                <a href="#" class="fav-nav"><img src="/static/img/core-img/favorites.png" alt=""> Favourite</a>
                <a href="#" class="search-nav"><img src="/static/img/core-img/search.png" alt=""> Search</a>
            </div>
            <!-- Social Button -->
            <div class="social-info d-flex justify-content-between">
                <a href="#"><i class="fa fa-pinterest" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-instagram" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a>
                <a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a>
            </div>
        </header>
        <!-- Header Area End -->
    {% block content %}
        <!-- Product Catagories Area Start -->
        <div class="products-catagories-area clearfix">
            <div class="amado-pro-catagory clearfix">
                {% load static %}
                <!-- Single Catagory -->
                {% for product in object_list %}

                    <div class="single-products-catagory clearfix">
                    <a href="{% url 'product:category' product.name %}">
                        <img src="{{ product.image.url }}" alt="">
                        <!-- Hover Content -->
                        <div class="hover-content">
                            <div class="line"></div>
                            <p>From $180</p>
                            <h4>{{ product.name }}</h4>
                        </div>
                    </a>
                </div>

                {% endfor %}

            </div>
        </div>
        <!-- Product Catagories Area End -->
    </div>
    <!-- ##### Main Content Wrapper End ##### -->
{% endblock %}

    <!-- ##### Newsletter Area Start ##### -->
    <section class="newsletter-area section-padding-100-0">
        <div class="container">
            <div class="row align-items-center">
                <!-- Newsletter Text -->
                <div class="col-12 col-lg-6 col-xl-7">
                    <div class="newsletter-text mb-100">
                        <h2>Subscribe for a <span>25% Discount</span></h2>
                        <p>Nulla ac convallis lorem, eget euismod nisl. Donec in libero sit amet mi vulputate consectetur. Donec auctor interdum purus, ac finibus massa bibendum nec.</p>
                    </div>
                </div>
                <!-- Newsletter Form -->
                <div class="col-12 col-lg-6 col-xl-5">
                    <div class="newsletter-form mb-100">
                        <form action="#" method="post">
                            <input type="email" name="email" class="nl-email" placeholder="Your E-mail">
                            <input type="submit" value="Subscribe">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ##### Newsletter Area End ##### -->

    <!-- ##### Footer Area Start ##### -->
    <footer class="footer_area clearfix">
        <div class="container">
            <div class="row align-items-center">
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-4">
                    <div class="single_widget_area">
                        <!-- Logo -->
                        <div class="footer-logo mr-50">
                            <a href="index.html"><img src="/static/img/core-img/logo2.png" alt=""></a>
                        </div>
                        <!-- Copywrite Text -->
                        <p class="copywrite"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a> & Re-distributed by <a href="https://themewagon.com/" target="_blank">Themewagon</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                    </div>
                </div>
                <!-- Single Widget Area -->
                <div class="col-12 col-lg-8">
                    <div class="single_widget_area">
                        <!-- Footer Menu -->
                        <div class="footer_menu">
                            <nav class="navbar navbar-expand-lg justify-content-end">
                                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#footerNavContent" aria-controls="footerNavContent" aria-expanded="false" aria-label="Toggle navigation"><i class="fa fa-bars"></i></button>
                                <div class="collapse navbar-collapse" id="footerNavContent">
                                    <ul class="navbar-nav ml-auto">
                                        <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'index' %}">Home</a>
                                        </li>
                                        {% if user.is_authenticated %}
                                            <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'index' %}">Cart</a>
                                            </li>
                                            <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'index' %}">Checkout</a>
                                            </li>
                                            <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'index' %}">Profile</a>
                                            </li>

                                        {% else %}
                                           <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'account:register' %}">SignUp</a>
                                            </li>
                                            <li class="nav-item active">
                                            <a class="nav-link" href="{% url 'account:login' %}">LogIn</a>
                                            </li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- ##### Footer Area End ##### -->
    <!-- ##### jQuery (Necessary for All JavaScript Plugins) ##### -->
    <script src="/static/js/jquery/jquery-2.2.4.min.js"></script>
    <!-- Popper js -->
    <script src="/static/js/popper.min.js"></script>
    <!-- Bootstrap js -->
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- Plugins js -->
    <script src="/static/js/plugins.js"></script>
    <!-- Active js -->
    <script src="/static/js/active.js"></script>


</body>

</html>