OnlineShop_Project/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from product.views import IndexCategories
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', IndexCategories.as_view(), name='index'),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls'))
    path('accounts/', include(('user.urls', 'user'), namespace='account')),
    path('products/', include(('product.urls', 'product'), namespace='product')),
    path('orders/', include(('order.urls', 'order'), namespace='order')),
    path('api-auth/', include('rest_framework.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/api/v1/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('cartdetail/', CartDetailList.as_view(), name='detail_create'),
    path('detail/<int:pk>/', CartItemDetail.as_view(), name='item_detail'),
    path('additem/', CartItemAddView.as_view(), name='add_item')
]

order/urls.py
from django.urls import path, include

from user.views import AddressCreateView
from .views import *

urlpatterns = [
    path('api/v1/', include(('order.api.v1.urls', 'api'), namespace='api')),
    path('cart/add/<str:product_name>/', ItemAddView.as_view(), name='item_add'),
    path('cartdetail/', CartView.as_view(), name='cart_detail'),
    path('cart/remove/<str:product_name>/', ItemRemoveView.as_view(), name='item_remove'),
    path('cart/create/', UserCartCreateView.as_view(), name='usercart_create'),
    path('cart/adddetail/', AddCartDetailView.as_view(), name='cartdetail_create'),
    path('usercart/', UserCartListView.as_view(), name='usercart_list'),
    path('addqty/<str:product>/', AddItemQtyView.as_view(), name='add_qty'),
    path('minusqty/<str:product>/', MinusItemQtyView.as_view(), name='minus_qty'),
    path('checkout/', CheckOutView.as_view(), name='checkout'),
    path('add_address/<str:slug>/', AddressCreateView.as_view(template_name='order/add_address.html'), name='add_checkout_address'),

]

user/urls.py
from django.contrib.auth.views import PasswordChangeView
from django.urls import path
from .views import *


urlpatterns = [
    # path('', AdminIndex.as_view(), name='admin_index'),
    path('register/', RegisterPage.as_view(), name='register'),
    path('login/', LoginPage.as_view(), name='login'),
    path('logout/', LogoutPage.as_view(), name='logout'),
    path('verify/', UserVerify.as_view(), name='verify'),
    path('reset/', UserPasswordReset.as_view(), name='reset_password'),
    path('reset-done/', UserPasswordResetDone.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', PasswordResetConfirm.as_view(), name='password_reset_confirm'),
    path('confirm-complete/', PasswordResetComplete.as_view(), name='password_reset_complete'),
    path('profile/<str:slug>/', UserDetailView.as_view(), name='user_profile'),
    path('editprofile/<str:slug>/', UserEditView.as_view(), name='user_edit'),
    path('changepass/<str:slug>/', UserPasswordChangeView.as_view(template_name='account/change_password.html'), name='change_password'),
    path('set_default_address/<int:new_ad>/', SetDefaultAddress.as_view(), name='set_default_address'),
    path('add_address/<str:slug>/', AddressCreateView.as_view(), name='add_address'),
]

order/forms.py
from django import forms


class CartAddForm(forms.Form):
    qty = forms.IntegerField(min_value=1, max_value=300)


class CartDetailForm(forms.Form):
    total_amount = forms.FloatField()
    shipping = forms.CharField(max_length=10)

order/api/v1/views.py
from datetime import date
from rest_framework.response import Response
from rest_framework import status, mixins, generics

from product.models import Product
from .serializers import CartDetailSerializer, CartItemSerializer, ProductSerializer, CartItemFormSerializer
from rest_framework.views import APIView

from ...models import CartItem, CartDetail, UserCart, ShippingMethod

data = {
    'id': 24,
    'title': "my dear",
}


class CartDetailList(APIView):
    def post(self, request, *args, **kwargs):
        cart_id = UserCart.user_open_cart(request.user)
        order_date = date.today()
        shipping_name = request.data['shipping']
        shipping_obj = ShippingMethod.objects.get(name=shipping_name)
        shipping_price = shipping_obj.price
        total_amount = float(request.data['total_amount']) + shipping_price
        serializer = CartDetailSerializer(data={
            'cart_id': cart_id,
            'order_date': order_date,
            'shipping_id': shipping_obj,
            'total_amount': total_amount
        })
        if serializer.is_valid():
            serializer.save()
        return Response(serializer.data)


class CartItemDetail(mixins.RetrieveModelMixin,
                     mixins.UpdateModelMixin,
                     mixins.DestroyModelMixin,
                     generics.GenericAPIView):
    queryset = CartDetail.objects.all()
    serializer_class = CartDetailSerializer

    def get(self, request, *args, **kwargs):
        return self.retrieve(request, *args, **kwargs)

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class CartItemAddView(mixins.CreateModelMixin,
                      generics.GenericAPIView):
    queryset = CartItem.objects.all()
    serializer_class = CartItemSerializer

    def post(self, request, *args, **kwargs):
        product = request.POST['product']
        print('product', product)
        qty = request.POST['qty']
        cart_id = UserCart.user_open_cart(request.user).id
        serializer = CartItemFormSerializer(data={
            'product_name': product,
            'qty': int(qty),
            'cart_id': cart_id,
        })
        if serializer.is_valid():
            product = Product.objects.get(slug=product)
            qty = int(request.POST['qty'])
            cart_id = UserCart.user_open_cart(request.user)
            CartItem.objects.create(product=product, qty=qty, cart_id=cart_id)
            headers = self.get_success_headers(serializer.data)
            return Response(serializer.data, status=status.HTTP_201_CREATED, headers=headers)

        headers = self.get_success_headers(serializer.data)
        return Response(serializer.data, status=status.HTTP_202_ACCEPTED, headers=headers)

order/views.py
from datetime import date

from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views import View
from product.models import Product
from .utils import CartSession
from .forms import CartAddForm, CartDetailForm
from django.shortcuts import redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import UserCart, CartItem, CartDetail, ShippingMethod


class CartView(View):
    """
    showing user cart info with request session data
    """

    def get(self, request):
        """
        using request ro access session cart values ( with SessionCart utils )
        :return:
        """
        cart = CartSession(request)
        context = {
            'cart': cart,
            'total_amount': cart.total_price(),
            'discount_price': cart.cart_discount_price(),
            'final_price': cart.cart_final_price(),
            'shipping': ShippingMethod.objects.all(),
        }

        return render(request, 'order/cart.html', context)


class ItemAddView(View):
    """
    this view is for add to cart button
    uses request session to store cart item values in cart session
    """

    def post(self, request, product_name):
        cart = CartSession(request)
        product = get_object_or_404(Product, name=product_name)
        form = CartAddForm(request.POST)

        if form.is_valid():
            # checks product stock with ordered qty
            if product.qty >= form.cleaned_data['qty']:
                cart.add(product, form.cleaned_data['qty'])
            else:
                messages.info(request, 'insufficient quantity :(')
        #  redirect to remain on the current page
        return redirect(request.META.get('HTTP_REFERER'))


class ItemRemoveView(View):
    """
    this view deletes items from cart ( in request session )
    """

    def get(self, request, product_name):
        cart = CartSession(request)
        # product = get_object_or_404(Product, name=product_name)
        # cart.remove(product)
        cart.remove(product_name)
        return redirect('order:cart_detail')


class UserCartCreateView(LoginRequiredMixin, View):
    """
    this view creates UserCart object for user in db
    & creates cart items in CartItem
    """

    def get(self, request):
        cart = CartSession(request)
        usercart = UserCart.user_open_cart(request.user)
        usercart_id = usercart.id
        for item in cart:
            CartItem.objects.create(cart_id_id=usercart_id,
                                    product_id=item['name'],
                                    qty=item['qty']
                                    )
            product = Product.objects.get(name=item['name'])
            product.qty -= item['qty']
            product.save()

        cart.clear()
        usercart.entry = True
        usercart.save()
        return redirect('order:usercart_list')


class AddCartDetailView(LoginRequiredMixin, View):
    """
    this view gets cart detail value & add to db
    create CartDetail object
    :redirect ro add cart item view(UserCartCreateView)
    """

    def post(self, request):
        form = CartDetailForm(request.POST)
        if form.is_valid():
            cart_id = UserCart.user_open_cart(request.user).id
            order_date = date.today()
            shipping_name = form.cleaned_data['shipping']
            shipping_obj = ShippingMethod.objects.get(name=shipping_name)
            shipping_price = shipping_obj.price
            total_amount = form.cleaned_data['total_amount'] + shipping_price
            CartDetail.objects.create(cart_id_id=cart_id, order_date=order_date, shipping_id=shipping_obj,
                                      total_amount=total_amount)

        return redirect('order:usercart_create')
        # return redirect('order:cart_detail')


class UserCartListView(LoginRequiredMixin, View):
    """
    this view filters user's carts that are checked out (entry = True)
    """

    def get(self, request):
        carts = UserCart.objects.filter(user_id=request.user)
        return render(request, 'order/cart_list.html', {'carts': carts})


class AddItemQtyView(View):
    def get(self, request, product):
        cart = CartSession(request)
        cart.add_qty(product)
        return redirect('order:cart_detail')


class MinusItemQtyView(View):
    def get(self, request, product):
        cart = CartSession(request)
        cart.minus_qty(product)
        return redirect('order:cart_detail')


class CheckOutView(LoginRequiredMixin, View):

    def get(self, request):
        cart = CartSession(request)
        if len(cart):
            context = {
                'user': request.user,
                'cart': cart,
                'total_amount': cart.total_price(),
                'discount_price': cart.cart_discount_price(),
                'final_price': cart.cart_final_price(),
                'shipping': ShippingMethod.objects.all(),
            }
            return render(request, 'order/checkout.html', context=context)
        else:
            messages.info(request, 'Your Cart Is Empty')
            return redirect(request.META.get('HTTP_REFERER'))

    def post(self, request):
        return redirect('order:checkout')

# API

from rest_framework.reverse import reverse
import requests as client
DOMAIN = "http://127.0.0.1:8000"
class ApiAddItem(View):
    def post(self, request, product_name):
        cart = CartSession(request)
        usercart = UserCart.user_open_cart(request.user)
        usercart_id = usercart.id
        endpoint = reverse('order:api:v1:item_list')
        for item in cart:
            product = Product.objects.get(name=item['name'])
            print('{DOMAIN}{endpoint}')
            a = client.post(f"{DOMAIN}{endpoint}", data={
                'cart_id': usercart,
                'product': product,
                'qty': item['qty']
            })
            print(a)
            # CartItem.objects.create(cart_id_id=usercart_id,
            #                         product_id=item['name'],
            #                         qty=item['qty']
            #                         )

        cart.clear()
        usercart.entry = True
        usercart.save()
        return redirect('order:usercart_list')



class CartDetailApi(View):
    def post(self, request):
        form = CartDetailForm(request.POST)
        if form.is_valid():
            cart_id = UserCart.user_open_cart(request.user).id
            order_date = date.today()
            shipping_name = form.cleaned_data['shipping']
            shipping_obj = ShippingMethod.objects.get(name=shipping_name)
            shipping_price = shipping_obj.price
            total_amount = form.cleaned_data['total_amount'] + shipping_price
            endpoint = reverse('order:api:item_list')
            client.post(f"{DOMAIN}{endpoint}", data={
              'cart_id': cart_id,
              'order_date': order_date,
              'shipping_id': shipping_obj,
              'total_amount': total_amount
            })
            # CartDetail.objects.create(cart_id_id=cart_id, order_date=order_date, shipping_id=shipping_obj,
            #                           total_amount=total_amount)

        return redirect('order:usercart_create')

templates/order/cart.html
{% extends 'product/index.html' %}
{% load static %}
{% block content %}

    <div class="cart-table-area section-padding-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-8">
                {% block cartinfo %}
                    <div class="cart-title mt-50">
                    {% for message in messages %}
                            {% if forloop.last %}
                                <p class="mb-4" style="color: indianred">{{ message }}</p>
                            {% endif %}
                        {% endfor %}
                        <h2>Shopping Cart</h2>
                    </div>

                    <div class="cart-table clearfix">
                        <table class="table table-responsive">
                            <thead>
                            <tr>
                                <th></th>
                                <th>Name</th>
                                <th>Price</th>
                                <th>Quantity</th>

                            </tr>
                            </thead>
                            <tbody>


                            {% for item in cart %}

                                <tr>
                                    <td class="cart_product_img">
                                        {#                                            <a href="#"><img src="../../static/img/bg-img/cart1.jpg" alt="Product"></a>#}
                                        <a href="{% url 'product:detail' item.name %}"><img src="{{ item.img }}"
                                                                                            width="150" height="150"
                                                                                            alt="Product">
                                        {#                                                {{ item.img }}#}
                                    </td>
                                    <td class="cart_product_desc">
                                        <h5>{{ item.name }}</h5>
                                    </td>
                                    <td class="price">
                                            <span>
                                                {% if item.price_discount %}
                                                    <del>${{ item.price }}</del>
                                                    <span style="color: red"> ${{ item.price_discount }}</span>
                                                {% else %}
                                                    ${{ item.price }}

                                                {% endif %}
                                            </span>
                                    </td>
                                    <td class="qty">
                                        <div class="qty-btn d-flex">
                                            {#                                                <p>Qty</p>#}
                                            <div class="quantity">
                                                <a href="{% url 'order:minus_qty' item.name %}"><span class="qty-minus"><i
                                                        class="fa fa-minus" aria-hidden="true"></i></span></a>
                                                <input type="number" class="qty-text" id="qty" step="1" min="1"
                                                       max="300" name="quantity" value={{ item.qty }}>
                                                <input type="hidden" value={{ item.qty }}>
                                                <a href="{% url 'order:add_qty' item.name %}"> <span class="qty-plus"><i
                                                        class="fa fa-plus" aria-hidden="true"></i></span></a>
                                            </div>
                                            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                            <a href="{% url 'order:item_remove' item.name %}">
                                            <button type="button" class="btn btn-outline-warning" value="Remove">
                                                REMOVE
                                            </button>
                                            </a>
                                        </div>

                                    </td>
                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
                <div class="col-12 col-lg-4">
{#                    <form action="{% url 'order:api:detail_create' %}" method="post" name="cartdetail">#}
                    <form action="{% url 'order:checkout' %}" method="post" name="cartdetail">
                    {% csrf_token %}
                    <div class="cart-summary">

                        <h5>Cart Open</h5>
                        <ul class="summary-table">
                            <li><span>total:</span> <span>${{ total_amount }}</span></li>
                            <li><span>discount:</span> <span style="color: red">- ${{ discount_price }}</span></li>
                            <li><span>final:</span> <span id="final_price">${{ final_price }}</span></li>
    {#                        <li><span>status:</span> <span id="final_price">OPEN</span></li>#}
                            <li><span>delivery:</span> <span>
                                                        <select name="shipping" id="shipping">
    {#                                                    <option value="saab">Saab</option>#}
    {#                                                    <option value="mercedes">Mercedes</option>#}
    {#                                                    <option value="audi">Audi</option>#}

                                                            {% for s in shipping %}
    {#                                                        <input type="radio" name="shipping">{{ s }}#}
    {#                                                        <br><br>#}
                                                            <option id="shipping_option" value="{{ s.name }}">{{ s.name }} : ${{ s.price }}</option>

                                                            {% endfor %}

                                                        </select>

                                                        </span></li>
{#                        <li><span>Address:  </span><span>{{ request.user.default_address }}</span></li>#}
{#                        <li><a href="{% url 'account:user_edit' request.user.slug %}" style="color: #b6843a">Edit Address & Info Here</a> </li>#}
{#                        </ul>#}
                    <div class="cart-btn mt-100">
{#                        <form action="{% url 'order:cartdetail_create' %}" method="post" name="cartdetail">#}
{#                        {% csrf_token %}#}

                            <input type="hidden" value={{ final_price }} name="total_amount">
{#                            <input type="hidden" value= name="shipping">#}
                            <button type="submit" class="btn amado-btn w-100" name="submit">Checkout</button>
                    </div>
                    </div>
                    </form>
                    </div>
            </div>
        </div>
    </div>
    </div>
    </div>


    {% endblock cartinfo %}

{% endblock %}

templates/order/checkout.html
{% extends 'product/index.html' %}
{% load static %}
{% block content %}




    <div class="cart-table-area section-padding-100">
        <div class="container-fluid">
            <div class="row">
                <div class="col-12 col-lg-8">
                {% block cartinfo %}

                    <div class="cart-title mt-50">
                        <h4 class="mb-4 mt-0">Your addresses<p>click on address to set default<a style="text-decoration: None; color: #dea55f" href="{% url 'order:add_checkout_address' request.user.slug %}"> Or Add New Address</a> </p></h4>

                    </div>

                    <div class="cart-table clearfix">
                    {% block addressinfo %}
                        <ul>
                        {% if not user.all_addresses %}
                        <li>no addresses yet</li>
                        {% else %}
                            {% for a in user.all_addresses %}
                                {% if a == user.default_address %}
                                    <li><span style="border-color: #ec9625;text-decoration: None;font-size: 15px; color: #dea55f;font-weight: 100;">
                                    <span class="fa fa-address-card" style="text-decoration: None; color: #ec9625">  {{ a }} </span>
                                    </span>
                                    <br><br>
                                {% else %}
                                    <li><a href="{% url 'account:set_default_address' a.id %}" style="text-decoration: None;font-size: 15px">
                                    <span class="fa fa-address-card" style="text-decoration: None; color: dimgrey">  {{ a }}</span>
                                    </a>
                                        <br><br>
                                {% endif %}
                            {% endfor %}

                        {% endif %}
                        </ul>
                    {% endblock addressinfo %}



                    </div>
                </div>
                <div class="col-12 col-lg-4">
{#                    <form action="{% url 'order:api:detail_create' %}" method="post" name="cartdetail">#}
                    <form action="{% url 'order:cartdetail_create' %}" method="post" name="cartdetail">
                    {% csrf_token %}
                    <div class="cart-summary">

                        <h5>Cart Open</h5>
                        <ul class="summary-table">
                            <li><span>total:</span> <span>${{ total_amount }}</span></li>
                            <li><span>discount:</span> <span style="color: red">- ${{ discount_price }}</span></li>
                            <li><span>final:</span> <span id="final_price">${{ final_price }}</span></li>
    {#                        <li><span>status:</span> <span id="final_price">OPEN</span></li>#}
                            <li><span>delivery:</span> <span>
                                                        <select name="shipping" id="shipping">
    {#                                                    <option value="saab">Saab</option>#}
    {#                                                    <option value="mercedes">Mercedes</option>#}
    {#                                                    <option value="audi">Audi</option>#}

                                                            {% for s in shipping %}
    {#                                                        <input type="radio" name="shipping">{{ s }}#}
    {#                                                        <br><br>#}
                                                            <option id="shipping_option" value="{{ s.name }}">{{ s.name }} : ${{ s.price }}</option>

                                                            {% endfor %}

                                                        </select>

                                                        </span></li>
{#                        <li><span>Address:  </span><span>{{ request.user.default_address }}</span></li>#}
{#                        <li><a href="{% url 'account:user_edit' request.user.slug %}" style="color: #b6843a">Edit Address & Info Here</a> </li>#}
{#                        </ul>#}
                    <div class="cart-btn mt-100">
{#                        <form action="{% url 'order:cartdetail_create' %}" method="post" name="cartdetail">#}
{#                        {% csrf_token %}#}

                            <input type="hidden" value={{ final_price }} name="total_amount">
{#                            <input type="hidden" value= name="shipping">#}
                            <button type="submit" class="btn amado-btn w-100" name="submit">Checkout</button>


                    </div>
                    </div>
                    </form>
                    </div>
            </div>
        </div>
    </div>
    </div>
    </div>




    {% endblock cartinfo %}

{% endblock %}